-- local colors_name = "matrixscheme"
-- vim.g.colors_name = colors_name -- Required when defining a colorscheme
--
-- local lush = require("lush")
-- local hsluv = lush.hsluv -- Human-friendly hsl
-- local util = require("zenbones.util")
--
-- local palette = util.palette_extend({
--   bg = hsluv("#000000"), -- Black background
--   fg = hsluv("#00FF00"), -- Green foreground
-- }, "dark")
--
-- -- Generate the lush specs using the generator util
-- local generator = require("zenbones.specs")
-- local base_specs = generator.generate(palette, "dark", generator.get_global_config(colors_name, "dark"))
--
-- -- Optionally extend specs using Lush
-- local specs = lush.extends({ base_specs }).with(function()
--   return {
--     Statement({ fg = palette.fg }),
--     Special({ fg = palette.fg }),
--     Type({ fg = palette.fg }),
--     Identifier({ fg = palette.fg }),
--     PreProc({ fg = palette.fg }),
--     Constant({ fg = palette.fg }),
--     Comment({ fg = palette.fg }),
--     Normal({ fg = palette.fg, bg = palette.bg }),
--     -- Add more highlight groups as needed
--   }
-- end)
--
-- -- Pass the specs to lush to apply
-- lush(specs)
--
-- -- Optionally set term colors
-- require("zenbones.term").apply_colors(palette)
